### ISSUE TITLE
资金管理记录

### ISSUE THREAD

**Issue by waheya** [eth-hangzhou/ETHHangzhou#1]
# ETH Hangzhou 资金管理

## 收入：$27000

ETH Foundation: $7000； 

Scroll: $5000；

ZAN：$5000；

BIXIN：$5000；

Chainlink：$2000；

FMG：$2000；

storytown: $1000;

### 除奖金外可支出预算：收入-奖金 =  $12000 = ¥86400

> 人数相关的支出，暂按 150人（学生50人）计算

1. 周边：

   - T恤（人均50左右）：150x50 = ¥7500
   - 。。。

2. 青旅（人均65人/晚）：65x50x3= ¥9750

3. 路费（暂定人均$50）：50x`$50` = `$2500` = ¥17500

4. 盒饭（人均15/人/餐）： 15 x 150 x 5 =  ¥11250

5. 场地费： 赞助，无费用

6. After Party：¥10000

7. 办公桌租赁(40/张/天+运费): 40x30x4 + 300 =¥1500

8. 物料：共计600+100+750+830+80+320=¥2680

   - 易拉宝(海报+指示牌)：4 x 150 = ¥600

   - 喷绘: ¥100

   - 工牌(均价¥5)： 5 x 150 = ¥750

   - 插排: 800+30 = ¥830
   - 免责书(200份)：¥80
   - Scroll Postcard,易拉宝+闪送: 150 + 150 + 20 = ¥320

9. 杂项：共计600=¥600

   - 矿泉水(20箱)：¥600

**Comment by DessertHeart** [comment]
住宿酒店⬇️：

青旅/酒店：新异青年旅社（65/人，预留50床位，押金2000[Dezso支付]）

**Comment by waheya** [comment]
周边T恤: 均价¥50, 定制150件, 共计¥7500(Omen支付)

**Comment by waheya** [comment]
物料工牌: 均价¥5, 定制150份, 共计¥750(Omen支付)

**Comment by DessertHeart** [comment]
桌子：30张，13-16四天每张40，来回人工费包装配共计300，共1500元
排插：小米8孔位×25，共计800元
（Dezso支付）
30 元跑腿费 (Omen支付)

**Comment by waheya** [comment]
易拉宝: 尺寸0.8x1.8m, 数量4, 单价150;
喷绘:尺寸0.6x6m,  数量1, 单价100;
共计750元
(Omen支付)

**Comment by DessertHeart** [comment]
免责协议：200×0.4 = 80元
Scroll Postcards：150元(200份)
工牌补打印：180
Scroll易拉宝：150
闪送：20
共580元
（Dezso支付）

**Comment by DessertHeart** [comment]
BIXIN：5000USDT(BINXIN) 以7.35汇率，换算为36750RMB（Dezso微信收）

Afterparty总价：10000元
13号晚饭：1035元

**Comment by waheya** [comment]
矿泉水（20箱）：三次订水，每次十箱300元，3×300=900元
（Oliver支付）

**Comment by DessertHeart** [comment]
14日-青旅尾款：7750元；14日午餐：85*15=1275元；14日晚餐：80*15=1200元
押金扣除：1000

**Comment by DessertHeart** [comment]
15、16餐费：3000（Oliver支付）

**Comment by AmazingAng** [comment]
收到Scroll赞助5000u
