### ISSUE TITLE
ETH Hangzhou PoW统计

### ISSUE THREAD

**Issue by DessertHeart** [eth-hangzhou/ETHHangzhou#61]
#### ⏰截止时间：2023年12月9日

1. **统计范围**
ETH Hangzhou Hackathon相关的一切贡献，包括网站开发/设计、外联、开发者运营、活动运营、物料准备、文案、现场志愿者等。

2. **统计方法**
以总贡献时长为准，请大家参考以下格式，在这个帖子下面回复自己的贡献情况。
    > **样例**：
    >
    > Alice（姓名）：（贡献总时长）
    > 
    > - 网站开发（参与事项）：5h（贡献时长）
    > - 现场志愿（参与事项）：5h（贡献时长）
    > ……

3. **审核方法**
每位贡献者自行填写并自审提交，由筹备组成员对公开信息进行检查，最后由负责人共同Review。

**Comment by Lawyergeek** [comment]
高杰：总贡献时长20h
现场志愿：5h
人员接待：15h（小助手等）

**Comment by DessertHeart** [comment]
Dezso：175h

- 活动策划与组织筹备：100h
- 联系赞助: 5h
- 对接嘉宾: 5h
- 网站项目管理：3h
- 活动场地对接与布置：24h
- 筛选开发者：2h
- 现场志愿: 36h

**Comment by LBruyne** [comment]
Hins (Xuanming):  20h
- 准备和主持一次圆桌讨论：不太好估计，先定个8h吧
- 现场志愿：12h

**Comment by ThunderAlalei** [comment]
Ray:50h

Logo设计：5h
PR稿设计：6h
AMM海报设计：6h
Poap设计：4h
网站设计：8h
长海报+易拉宝：4h
其余物料设计+对接嘉宾设计：12h
现场志愿：5h

**Comment by Quynhs** [comment]
宋金舰：总贡献时长9h
Logo设计：2h
现场志愿：5h
对接、沟通推文制作：1.5h
对接服装物资：0.5h

**Comment by waheya** [comment]
Omen:

**Comment by hubingliang** [comment]
Brian: 8h
网站开发：4h
物料替换：2h
需求沟通：2h

**Comment by waheya** [comment]
Omen: 46h
官网相关方案设计及开发： 12h
活动场地布置：8h
现场志愿：8h
文化衫定制及制作：6h
广告物料定制及制作：8h
资金花费统计： 4h

**Comment by KaiaXuan** [comment]
凯旋：75h
现场志愿：24h

场间主持：16h

前期BD网站：2h
1. 网站检查会议 1h
2. BDdeck参写撰写 1h

志愿者管理：18h
1. 外部志愿者报名表+协会内报名：2h
2. 筛选时间充裕的志愿者，答疑指导志愿者上岗：8h
3. 志愿者协调排班：8h

嘉宾管理：15h
1. workshop排期：5h
2. 嘉宾、mentor报名统计：5h
3. 嘉宾对接：5h

**Comment by HEDDAZZ** [comment]
子涵：总贡献时长8h

现场志愿：4h
报名表制作：2h
推文制作：2h

**Comment by Assm995** [comment]
Assm：50h
1. 海报制作及后期修改：34h
     海报版本敲定（多次修改）：20h
     海报后期调整修改对接（多次调整）：10h
AMA海报：4h
2. 易拉宝制作和修改：3h
3. 官网banner设计：6h
     banner头图版本敲定（修改多次）：5h
    后期修改：1h
4. 志愿服务及拍照：7h
      现场拍照：4h
      志愿服务：7h

**Comment by OliverYF** [comment]
Oliver：总时长 108h

场地对接、布置：24h
酒吧对接、布置：12h
青旅对接：12h
餐饮对接：24h
押金收取、统计、退还：24h
现场志愿：12h

**Comment by RyanFcr** [comment]
Ryan
1. Panel：10h
2. 前期准备策划筹备：10h

**Comment by artistzxt** [comment]
Artist Zhou:  总时长 90h
1.筹备策划：20h
2.推文制作，宣发：30h
3.现场志愿：36h
4.Citywalk领队：4h

**Comment by SkyWuZJU** [comment]
**Sky Wu: 127h in all**

- **黑客松现场**：22h in all
1. 第四天demo day现场lead：主持、打分统计、评委协调等。12h
2. 第三天city walk协调：2h
3. 第二天Panel主持（两场）：5h
4. 第一天check in帮忙：3h

- **社群管理lead**：25h in all
1. 前期报名群: 通知编辑管理、群消息管理、群成员管理。20h
2. 后期选手群: 同上。5h

- **线上AMA lead（共6场）**：50h in all
1. 话题、内容设计
2. 嘉宾邀请、对接
3. 宣发物料准备、媒体对接
4. 主持（5场）

- **其他**：30h in all
1. BD Deck设计制作: 10h
2. 合作社区联系对接：5h
3. 赛后获奖团队对接：奖金发放对接、评委联系对接等。8h
4. 现场Panel的前期准备（2场）：物料准备、嘉宾对接。2h
5. 报名表筛选：2h
6. 媒体平台对接：3h

**ZJU&PKU LFGGGGG!**

**Comment by AmazingAng** [comment]
0xAA
100h
- 黑客松前期筹备: 30h
- 联系赞助商: 20h
- 联系场地 10h
- 宣传 10h
- 报名 10h
- 现场志愿者 10h
- 财务管理 10h

**Comment by hash-k-k** [comment]
Kiwi
40h

联系赞助商   20h
宣传支持cx队伍报名AMA等  10h
现场志愿与圆桌：10h

**Comment by DessertHeart** [comment]
嘉然：6H

- 作为 ama 嘉宾和准备 2H

- 公众号沟通和编辑 4H

**Comment by CClaudia031** [comment]
Claudia：40h

黑客松前期筹备：10h
联系赞助: 10h
宣传支持、AMA、CX队伍等：10h
现场志愿与圆桌：10h

**Comment by DessertHeart** [comment]
已发放
